### ISSUE TITLE
Writing m4a tags seems to render the file unplayable in some cases

### ISSUE THREAD

**Issue by milesegan** [Serial-ATA/lofty-rs#308] opened 2023-12-28 01:24 UTC
### Reproducer

```rust
use std::{
    fs::{copy, remove_file},
    path::Path,
    process::Command,
};

use lofty::{Accessor, Probe, Tag, TagExt, TagType, TaggedFileExt};

pub fn write_tag(dest: &Path) {
    let mut dest_file = Probe::open(&dest)
        .expect("can't open")
        .read()
        .expect("can't read");
    let tag = Tag::new(TagType::Mp4Ilst);
    let mut dest_tag = dest_file.insert_tag(tag).expect("no tag");
    dest_tag.set_artist("test artist".to_string());
    dest_tag.save_to_path(dest).expect("can't write");
}

fn main() {
    let _ = remove_file("encoded.m4a");
    let _ = remove_file("tagged.m4a");
    Command::new("afconvert")
        .args(["-d", "aac", "-f", "m4af", "test.flac", "encoded.m4a"])
        .output()
        .expect("couldn't encode file");
    println!("encoded to encoded.m4a");
    copy("encoded.m4a", "tagged.m4a").expect("copy failed");
    println!("copied to tagged.m4a");
    write_tag(Path::new("tagged.m4a"));
    println!("wrote tag to tagged.m4a");
}
```

### Summary

Writing a new tag to an m4a file seems to corrupt the file somehow and make it unplayable.

Running `afplay test.m4a` on the file generated above reports this error:

`Error: AudioQueueStart failed ('bada')`

And the file is also unplayable in the finder.

Note that this only seems to happen with m4a files created with `afconvert`. If I use ffmpeg to transcode the flac file to m4a and then write the tag with lofty the resulting file is playable.

### Expected behavior

The file should still be a playable m4a file after writing the tag.

### Assets

https://github.com/milesegan/lofty-m4a-bug

**Comment by Serial-ATA** [comment] 2023-12-28 18:18
Thanks for the report and all the information. Could you also provide the file created with `afconvert` prior to running it through Lofty? I do not have access to `afconvert` (I think?).

**Comment by milesegan** [comment] 2023-12-29 00:31
Sorry about that. I've updated the repo to include the file before tagging and I'm also attaching it here. I believe `afconvert` is part of the OS on Macs but that's the only way to get access to it.

Thanks for all your work on lofty, by the way!

[encoded.m4a.zip](https://github.com/Serial-ATA/lofty-rs/files/13790211/encoded.m4a.zip)

**Comment by Serial-ATA** [comment] 2023-12-29 18:47
Awesome, thanks!

I'm pretty sure this is just caused by the offset atoms, which need to be updated anytime the position of atoms change. I forgot they existed, since I don't have any files using them in my library. I'll try and get that fixed in the next couple days.

**Comment by milesegan** [comment] 2023-12-30 02:08
Thanks for your quick attention on this!

This year I'm going to try to help you out with some of the `good first issue` issues.

**Comment by Serial-ATA** [comment] 2024-01-02 05:48
Could you try out #318 and see if it fixes the issue for you?

**Comment by milesegan** [comment] 2024-01-02 08:45
Yep it seems to be working now. Thanks for the quick fix!

**Closed** 2024-01-02 18:23 UTC
Labels: bug
