### ISSUE TITLE
Artist is not saved for flac

### ISSUE THREAD

**Issue by tramhao** [Serial-ATA/lofty-rs#24] opened 2021-12-30 04:39 UTC
I write with below code and found that the artist printed is correct, but not saved. Other info like album,title,photo,lyrics are saved. I checked with kid3 and found artist is empty, other fields are ok.
```rust
                    tag.set_artist(
                        self.artist()
                            .map_or_else(|| String::from("Unknown Artist"), str::to_string),
                    );
                    println!("artist is {} now", tag.artist().unwrap());

```

**Comment by Serial-ATA** [comment] 2021-12-30 14:32
That's weird. Do you know if it works with Opus or Vorbis?

**Comment by Serial-ATA** [comment] 2021-12-30 18:22
I can't reproduce this.

```rust
    let mut file = Probe::open("test.flac").unwrap().read(false).unwrap();
    
    let tag = file.primary_tag_mut().unwrap();
    
    tag.set_artist("test artist".to_string());
    tag.save_to_path("test.flac").unwrap();
```

![Screenshot_lm _2021-12-30_01](https://user-images.githubusercontent.com/69764315/147778231-978276a5-8fcc-4938-b265-67fbf27443be.png)

**Comment by tramhao** [comment] 2021-12-31 02:17
I tested again with the opus and flac file from assets folder of lofty, again the artist is not saved for flac, but opus is fine.

**Comment by tramhao** [comment] 2021-12-31 02:19
For ogg the artist is saved too. I'm using git version #5808d44aa98ff0268ddcabb0ee4c91a93ecf5521 of lofty.

**Comment by tramhao** [comment] 2021-12-31 02:23
I commented out my code for saving lyric and picture, but didn't help. It's not related to flac artist saving.

**Comment by Serial-ATA** [comment] 2021-12-31 03:04
> I tested again with the opus and flac file from assets folder of lofty, again the artist is not saved for flac, but opus is fine.

I tested that file too, and had no issue. Can you send the file after using `set_artist`?

**Comment by tramhao** [comment] 2021-12-31 05:34
yes of course
[a.docx](https://github.com/Serial-ATA/lofty-rs/files/7795404/a.docx)
.

**Comment by tramhao** [comment] 2021-12-31 05:35
please rename the extension to flac.

**Comment by Serial-ATA** [comment] 2021-12-31 07:13
Hm, it really is just not writing the artist. That's weird since the same logic is shared between Opus, Vorbis, and FLAC.

**Comment by Serial-ATA** [comment] 2021-12-31 07:23
> ```rust
>     let mut file = Probe::open("test.flac").unwrap().read(false).unwrap();
>     
>     let tag = file.primary_tag_mut().unwrap();
>     
>     tag.set_artist("test artist".to_string());
>     tag.save_to_path("test.flac").unwrap();
> ```

Does this work? I was able to set the artist of that file with this.

**Comment by tramhao** [comment] 2021-12-31 08:20
Yes, I set artist successfully with the code you posted also.
So problem is here:
```rust
                if let Some(file_path) = self.file() {
                    let target_tag_type = match self.file_type {
                        Some(FileType::AIFF | FileType::MP3 | FileType::WAV) => TagType::Id3v2,
                        Some(FileType::APE) => TagType::Ape,
                        Some(FileType::MP4) => TagType::Mp4Ilst,
                        Some(FileType::Opus | FileType::Vorbis | FileType::FLAC) => {
                            TagType::VorbisComments
                        }
                        None => return Ok(()),
                    };

                    let mut tag = lofty::Tag::new(target_tag_type);

                    tag.set_artist(
                        self.artist()
                            .map_or_else(|| String::from("Unknown Artist"), str::to_string),
                    );
                    tag.set_title(
                        self.title()
                            .map_or_else(|| String::from("Unknown Title"), str::to_string),
                    );
                    tag.set_album(
                        self.album()
                            .map_or_else(|| String::from("Unknown Album"), str::to_string),
                    );

                    if !self.lyric_frames_is_empty() {
                        if let Some(lyric_frames) = self.lyric_frames() {
                            for l in lyric_frames {
                                tag.insert_text(ItemKey::Lyrics, l.text);
                            }
                        }
                    }

                    if let Some(any_picture) = self.picture().cloned() {
                        tag.push_picture(any_picture);
                        // if let Some(front_cover) = tag.get_picture_type(PictureType::CoverFront).cloned() {
                        // tag.push_picture(front_cover);
                    }

                    tag.save_to_path(file_path)?;
                }
```

**Comment by tramhao** [comment] 2021-12-31 08:21
I know that in some specifications the artist is a vector. Maybe the data is lost during conversion?

**Comment by tramhao** [comment] 2021-12-31 09:04
If I use Probe::open, it's ok. If I use Tag::new() . Artist is not written. Other fields are no problem.

**Comment by Serial-ATA** [comment] 2021-12-31 14:15
> If I use Probe::open, it's ok. If I use Tag::new() . Artist is not written. Other fields are no problem.

Ah, that was it. It should be fixed in https://github.com/Serial-ATA/lofty-rs/commit/b42b423c5084d6036124f0fac807311d1fb7c8a0. Could you try it out?

**Comment by tramhao** [comment] 2022-01-01 09:02
I tested with https://github.com/Serial-ATA/lofty-rs#075e0e692f2d6af96ae69d29d294a01085408778 and it works perfectly! Would you please publish a new version? Thanks.

**Comment by Serial-ATA** [comment] 2022-01-01 09:21
Thanks! I'll get this published tomorrow.

**Closed by Serial-ATA** 2022-01-01 09:21 UTC
Labels: bug
